version: '3.0'
services:
    couchbase:
      build:
        context: .
        dockerfile: couchbase/Dockerfile
      ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
      environment:
          - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
          - COUCHBASE_ADMINISTRATOR_PASSWORD=password
          - COUCHBASE_BUCKET=default
          - COUCHBASE_BUCKET_PASSWORD=password
 
    app:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - 3000:3000
            - 3333:3333
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
            - APPLICATION_PORT=3000
            - CLIENT_PORT=3333 
            - SERVER_PORT=3000
            - SECRET_KEY=IJNDIJDMCJ)(I#Q)+OE|}OPKDAOKD))00-00-=8977989+20=0=okl;lp],po[lp[p]]
        restart: always