version: '3.0'
services:
    couchbase:
      build:
        context: .
        dockerfile: couchbase/Dockerfile
      ports:
          - 8091:8091
          - 8092:8092
          - 8093:8093
      environment:
          - COUCHBASE_ADMINISTRATOR_USERNAME
          - COUCHBASE_ADMINISTRATOR_PASSWORD
          - COUCHBASE_BUCKET
          - COUCHBASE_BUCKET_PASSWORD
 
    app:
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
            - 3000:3000
            - 3333:3333
        environment:
            - COUCHBASE_HOST
            - COUCHBASE_BUCKET
            - COUCHBASE_BUCKET_PASSWORD
            - APPLICATION_PORT
            - CLIENT_PORT
            - SERVER_PORT
            - SECRET_KEY
        restart: always